### ISSUE TITLE
Warning: could not load plugin

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-cli-py#48] opened 2016-01-12 22:34 UTC
I installed with `sudo pip install mapboxcli` and I get the following when running `mapbox`. I haven't made much progress debugging myself. Any idea what's going on?

```
$ mapbox
Usage: mapbox [OPTIONS] COMMAND [ARGS]...

  This is the command line interface to Mapbox web services.

  Mapbox web services require an access token. Your token is shown on the
  https://www.mapbox.com/developers/api/ page when you are logged in. The
  token can be provided on the command line

    $ mapbox --access-token MY_TOKEN ...

  as an environment variable named MAPBOX_ACCESS_TOKEN (higher precedence)
  or MapboxAccessToken (lower precedence).

    $ export MAPBOX_ACCESS_TOKEN=MY_TOKEN
    $ mapbox ...

  or in a config file

    ; configuration file mapbox.ini
    [mapbox]
    access-token = MY_TOKEN

  The OS-dependent default config file path is something like

    ~/Library/Application Support/mapbox/mapbox.ini
    ~/.config/mapbox/mapbox.ini
    ~/.mapbox/mapbox.ini

Options:
  --version            Show the version and exit.
  -v, --verbose        Increase verbosity.
  -q, --quiet          Decrease verbosity.
  --access-token TEXT  Your Mapbox access token.
  -c, --config PATH    Config file
  --help               Show this message and exit.

Commands:
  config       † Warning: could not load plugin. See `mapbox config --help`.
  dataset      † Warning: could not load plugin. See `mapbox dataset --help`.
  directions   † Warning: could not load plugin. See `mapbox directions
               --help`.
  distance     † Warning: could not load plugin. See `mapbox distance --help`.
  geocoding    † Warning: could not load plugin. See `mapbox geocoding
               --help`.
  mapmatching  † Warning: could not load plugin. See `mapbox mapmatching
               --help`.
  staticmap    † Warning: could not load plugin. See `mapbox staticmap
               --help`.
  surface      † Warning: could not load plugin. See `mapbox surface --help`.
  upload       † Warning: could not load plugin. See `mapbox upload --help`.
```

**Comment by perrygeo** [comment] 2016-01-14 12:14
@willwhite - what does it report if you try one of the subcommands like `mapbox geocoding --help`?

**Comment by perrygeo** [comment] 2016-01-22 22:25
from chat

```
$ mapbox geocoding --help
Usage: mapbox geocoding [OPTIONS]

  Warning: entry point could not be loaded. Contact its author for help.

  Traceback (most recent call last):
    File "/Library/Python/2.7/site-packages/click_plugins/core.py", line 37, in decorator
      group.add_command(entry_point.load())
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2107, in load
      if require: self.require(env, installer)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2120, in require
      working_set.resolve(self.dist.requires(self.extras),env,installer)))
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
      raise VersionConflict(dist,req) # XXX put more info here
  VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.5'))

Options:
  --help  Show this message and exit.
```

My best guess is something on the system python requires an older version of six. 

The solution for python devs is to install in a virtual environment but this is a wider issue for those who want to install it globally.

cc @sgillies

**Comment by perrygeo** [comment] 2016-02-23 02:18
@willwhite we've got a new release and distributing it with homebrew. Can you try

```
brew install mapbox/cli/mapbox
```

and see if it works. We're trying to encourage brew as an alternative to `sudo pip install`.

**Comment by perrygeo** [comment] 2016-03-04 16:55
Closing for now, I'm not able to reproduce and no more reports so far. @willwhite - if you're still getting this error, we can reopen.

**Closed by perrygeo** 2016-03-04 16:55 UTC
Labels: packaging

**Comment by cbaze** [comment] 2016-08-25 02:39
I am having the same issue using Bash on Ubuntu on Windows
